const codeSnippets = {
    1: `#include <iostream>\nusing namespace std;\n\n// Вариант 1\n\n// Begin: Конвертация Цельсия в Фаренгейт\nfloat C, F;\ncin >> C;\nF = C * 9.0 / 5 + 32;\ncout << F << endl;\n\n// If: Проверка, является ли треугольник валидным\nint a, b, c;\ncin >> a >> b >> c;\nif (a + b > c && b + c > a && a + c > b) {\n    cout << "Yes" << endl;\n} else {\n    cout << "No" << endl;\n}\n\n// For: Сумма квадратов чисел от 1 до n\nint n, S = 0;\ncin >> n;\nfor (int i = 1; i <= n; i++) {\n    S += i * i;\n}\ncout << S << endl;\n\n// While: Сумма цифр числа\nint n2, s = 0;\ncin >> n2;\nwhile (n2 > 0) {\n    s += n2 % 10;\n    n2 /= 10;\n}\ncout << s << endl;\n\n// Series: Проверка убывания последовательности\nint n3, a, b, i = 2;\ncin >> n3 >> a;\nbool ok = true;\nwhile (i <= n3) {\n    cin >> b;\n    if (b <= a && ok) {\n        cout << i << endl;\n        ok = false;\n    }\n    a = b;\n    i++;\n}\nif (ok) {\n    cout << 0 << endl;\n}`,
    2: `#include <iostream>\nusing namespace std;\n\n// Вариант 2\n\n// Begin: Конвертация Фаренгейта в Цельсий\nfloat F, C;\ncin >> F;\nC = (F - 32) * 5.0 / 9;\ncout << C << endl;\n\n// If: Нахождение четвёртой точки через XOR\nint x1, y1, x2, y2, x3, y3;\ncin >> x1 >> y1 >> x2 >> y2 >> x3 >> y3;\nint x4 = x1 ^ x2 ^ x3;\nint y4 = y1 ^ y2 ^ y3;\ncout << x4 << " " << y4 << endl;\n\n// For: Сумма квадратов чисел от n до 2n\nint n, S = 0;\ncin >> n;\nfor (int i = n; i <= 2 * n; i++) {\n    S += i * i;\n}\ncout << S << endl;\n\n// While: Сумма и количество цифр числа\nint n2, sum = 0, count = 0;\ncin >> n2;\nwhile (n2 > 0) {\n    sum += n2 % 10;\n    count++;\n    n2 /= 10;\n}\ncout << "Sum = " << sum << ", Count = " << count << endl;\n\n// Series: Сумма положительных чисел в последовательности\nint n3, x, s = 0;\ncin >> n3;\nfor (int i = 0; i < n3; i++) {\n    cin >> x;\n    if (x > 0) s += x;\n}\ncout << s << endl;`,
    // Добавляйте коды для других вариантов здесь
    // Пример шаблона:
    // 3: `// Ваш код C++ для варианта 3\n#include <iostream>\nusing namespace std;\n\nint main() {\n    // Ваш код здесь\n    return 0;\n}`,
    // 4: `// Ваш код C++ для варианта 4\n#include <iostream>\nusing namespace std;\n\nint main() {\n    // Ваш код здесь\n    return 0;\n}`,
    // ...
    // 24: `// Ваш код C++ для варианта 24\n#include <iostream>\nusing namespace std;\n\nint main() {\n    // Ваш код здесь\n    return 0;\n}`
};
